kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/arunhari82/dotnet-eShopOnWeb.git'
    openshift.io/generated-by: OpenShiftWebConsole
  resourceVersion: '150359'
  name: public-api
  namespace: dotnet
  labels:
    app: public-api
    app.kubernetes.io/component: public-api
    app.kubernetes.io/instance: public-api
    app.kubernetes.io/name: public-api
    app.kubernetes.io/part-of: public-api
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'public-api:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: src/PublicApi/Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/arunhari82/dotnet-eShopOnWeb.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: public-api-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: public-api-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
