kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  namespace: dotnet
  labels:
     app: sqlserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem